# Generated by Django 5.1 on 2024-09-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='home_images'),
        ),
    ]
