# Generated by Django 5.1.1 on 2024-09-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_site', '0003_events_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('facebook_link', models.URLField()),
                ('insta_link', models.URLField()),
                ('youtube_link', models.URLField()),
                ('location_link', models.TextField(blank=True, null=True)),
                ('address', models.TextField()),
            ],
        ),
    ]
