# Generated by Django 5.1.1 on 2024-09-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_site', '0006_concerts_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(default='default.jpg', upload_to='blog_images'),
        ),
    ]
